apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wisecow-app
  labels: 
    app: wisecow-app
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wisecow-app
  template: 
    metadata: 
      labels: 
        app: wisecow-app
    spec:
      containers: 
        - name: wisecow-pod
          image: 767397832081.dkr.ecr.ap-northeast-2.amazonaws.com/accuknox:latest
          ports: 
            - containerPort: 4499
  
